# Generated by Django 4.0.3 on 2022-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sitioweb', models.URLField(max_length=100)),
                ('fundacion', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Compania',
                'verbose_name_plural': 'Companias',
            },
        ),
    ]
